### ISSUE TITLE
Look into why C implementation of "test.me" won't work on GH Actions.

### ISSUE THREAD

**Issue by ArielMAJ** [ArielMAJ/test.me#3] opened 2022-05-18 11:21 UTC
https://stackoverflow.com/questions/35215109/struct-dirent-does-not-have-de-type-in-header-file

Maybe it'll be necessary to change the way it access/iterates through folders.

**Comment by tauanesales** [comment] 2023-03-02 17:36
Duplicate of #10

**Closed by tauanesales** 2023-03-02 17:36 UTC
Labels: bug, duplicate
